### ISSUE TITLE
centos7下载更新后的的goctp编译失败

### ISSUE THREAD

**Issue by chenlongwill** [qerio/goctp#6]
/usr/bin/ld: cannot find -lthostmduserapi
/usr/bin/ld: cannot find -lthosttraderapi

**Comment by chenlongwill** [comment]
> /usr/bin/ld: cannot find -lthostmduserapi
> /usr/bin/ld: cannot find -lthosttraderapi

**Comment by leeyuanzhang** [comment]
How do you solve this problem?

**Comment by windwoo227** [comment]
ubuntu 也编译失败，不知道如何解决的？
# github.com/qerio/goctp
/usr/bin/ld: 找不到 -lthostmduserapi
/usr/bin/ld: 找不到 -lthosttraderapi
collect2: error: ld returned 1 exit status
# github.com/qerio/goctp
./api/SFIT_CTP_6.3.11_20180109_tradeapi/v6.3.11_20180109_api_tradeapi_linux64/ThostFtdcMdApi.h:30: Warning 514: Director base class CThostFtdcMdSpi has no virtual destructor.
./api/SFIT_CTP_6.3.11_20180109_tradeapi/v6.3.11_20180109_api_tradeapi_linux64/ThostFtdcTraderApi.h:30: Warning 514: Director base class CThostFtdcTraderSpi has no virtual destructor.
